version: '3.9'

services:
  db:
    image: mongo:latest
    restart: always
    container_name: mongoDB
    ports:
      - '27017:27017' # Default MongoDB port

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: default_app
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist # Optional: for accessing built files
      - ./tsconfig.json:/app/tsconfig.json # Optional: for tsconfig access
    environment:
      - NODE_ENV=development
